name: 031-dotnet-scan

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-scan-dotnet:

    runs-on: windows-latest # ubuntu-latest
    
    defaults:
      run:
        working-directory: 03-app-dotnet

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
  
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    # doc: https://github.com/dotnet/code-analysis
    - name: Run .NET Code Analysis
      uses: dotnet/code-analysis@main
      id: code-analysis
      with:
        projects: 03-app-dotnet\app-dotnet.csproj
        # solution: MySolution.sln
        build-breaking: true
        all-categories: all
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
