name: Call a reusable workflow

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]

jobs:
  call-workflow:
    uses: octo-org/example-repo/.github/workflows/workflow-A.yml@v1

  call-workflow-passing-data:
    uses: octo-org/example-repo/.github/workflows/workflow-B.yml@main
    with:
      username: Houssem
    secrets:
      token: ${{ secrets.TOKEN }}