name: Call a reusable workflow

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]

jobs:
  call-workflow:
    uses: HoussemDellai/github-actions-course/.github/workflows/080-reusable-workflow-called.yml@main

  call-workflow-passing-data:
    uses: HoussemDellai/github-actions-course/.github/workflows/080-reusable-workflow-called.yml@main
    with:
      username: Houssem
    secrets:
      token: ${{ secrets.TOKEN }}